name: Update Data API

on:
    schedule: 
        - cron: "5 0 * * *"

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: latest
            - run: npm install
            - run: node src/update.js
            - run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git add .
                  git commit -m "Update Data (Auto)"
                  git push
