name: Update Data

on:
  schedule:
    - cron: "10 10 15 * *"

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Add Package GitHub Action Metadata
      uses: actions/checkout@v3
    - name: Add Package GitHub NodeJS Setup
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'
    - name: Installing Package
      run: npm install
    - name: Updating All Datas
      run: node src/update.js
    - name: Creating Commit
      run: |
        date > last-update.txt
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update Data (Auto)"
        git push
