name: Update Data

on:
  push:
    branches:
      - main
  schedule: 
    - cron: "0 0 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'
    - name: Installing Package
    - run: npm install
    - name: Updating All Datas
    - run: node src/update.js
    - name: Creating Commit
    - run: |
        if [ -f last-update.txt ]
        then
          rm last-update.txt
        else
          date > last-update.txt
        fi
        
        git config user.name fadzikri
        git config user.email 109416385+fadzikri@users.noreply.github.com
        git add .
        git commit -m "Update Data (Auto)"
        git push
